# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Command to generate static files: 
# JEKYLL_ENV=production bundle exec jekyll build -d ../mac389.github.io --incremental --watch

# Site settings
title: The Chary Lab
email: mac389@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computational Toxiology, and (Nearly) Everything is Toxicology
url: "mac389.github.io"
baseurl: ""

include:
  - .htaccess
  - _pages

plugins: 
  - jekyll-sitemap
  - jekyll-spaceship

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

gems: 
  - jekyll/scholar
  - jekyll-seo-tag
  - jekyll-mermaid
  - jekyll-quicklatex

mermaid:
  src: './js/mermaid.js'

scholar:
  style: nature
  locale: en
  sort_by: [year,month]
  order: descending
  source: ./_bibliography
  bibliography: all-my-works.bib
  bibliography_template: "{{ reference | replace_first: 'Chary, M.', '<b>Chary, M.</b>' }}"
  bibtex_filters:
    - latex

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  mathjax: true
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

